
export type PartOfSpeech = 'Verb' | 'Noun' | 'Adverb' | 'Adjective' | 'Other';

export interface Word {
    id: string;
    kana: string; // The hiragana/katakana reading (e.g. ねこ)
    romaji: string; // The input target (e.g. neko)
    kanji: string; // The kanji representation (e.g. 猫)
    en: string; // English meaning (e.g. Cat)
    morae: number; // For difficulty scaling
    pos: PartOfSpeech; // Part of speech for color coding
}

export const WORDS: Word[] = [
    // 1 Morae
    { id: 'hi', kana: 'ひ', romaji: 'hi', kanji: '火', en: 'Fire', morae: 1, pos: 'Noun' },
    { id: 'ki', kana: 'き', romaji: 'ki', kanji: '木', en: 'Tree', morae: 1, pos: 'Noun' },
    { id: 'te', kana: 'て', romaji: 'te', kanji: '手', en: 'Hand', morae: 1, pos: 'Noun' },
    { id: 'me', kana: 'め', romaji: 'me', kanji: '目', en: 'Eye', morae: 1, pos: 'Noun' },
    { id: 'kyo', kana: 'きょう', romaji: 'kyo', kanji: '今日', en: 'Today', morae: 2, pos: 'Adverb' }, // Kyo-u is today (2 morae). Wait, "Today" is Kyou (2). Kyo alone is rare. Let's strictly use Kyou.
    // 2 Morae
    { id: 'neko', kana: 'ねこ', romaji: 'neko', kanji: '猫', en: 'Cat', morae: 2, pos: 'Noun' },
    { id: 'inu', kana: 'いぬ', romaji: 'inu', kanji: '犬', en: 'Dog', morae: 2, pos: 'Noun' },
    { id: 'tori', kana: 'とり', romaji: 'tori', kanji: '鳥', en: 'Bird', morae: 2, pos: 'Noun' },
    { id: 'hana', kana: 'はな', romaji: 'hana', kanji: '花', en: 'Flower', morae: 2, pos: 'Noun' },
    { id: 'yuki', kana: 'ゆき', romaji: 'yuki', kanji: '雪', en: 'Snow', morae: 2, pos: 'Noun' },
    { id: 'kaze', kana: 'かぜ', romaji: 'kaze', kanji: '風', en: 'Wind', morae: 2, pos: 'Noun' },
    { id: 'umi', kana: 'うみ', romaji: 'umi', kanji: '海', en: 'Sea', morae: 2, pos: 'Noun' },
    { id: 'sora', kana: 'そら', romaji: 'sora', kanji: '空', en: 'Sky', morae: 2, pos: 'Noun' },
    { id: 'yama', kana: 'やま', romaji: 'yama', kanji: '山', en: 'Mountain', morae: 2, pos: 'Noun' },
    { id: 'kawa', kana: 'かわ', romaji: 'kawa', kanji: '川', en: 'River', morae: 2, pos: 'Noun' },
    { id: 'ame', kana: 'あめ', romaji: 'ame', kanji: '雨', en: 'Rain', morae: 2, pos: 'Noun' },
    { id: 'eki', kana: 'えき', romaji: 'eki', kanji: '駅', en: 'Station', morae: 2, pos: 'Noun' },
    { id: 'michi', kana: 'みち', romaji: 'michi', kanji: '道', en: 'Road', morae: 2, pos: 'Noun' },
    { id: 'ie', kana: 'いえ', romaji: 'ie', kanji: '家', en: 'House', morae: 2, pos: 'Noun' },
    { id: 'machi', kana: 'まち', romaji: 'machi', kanji: '町', en: 'Town', morae: 2, pos: 'Noun' },
    { id: 'tera', kana: 'てら', romaji: 'tera', kanji: '寺', en: 'Temple', morae: 2, pos: 'Noun' },
    { id: 'hon', kana: 'ほん', romaji: 'hon', kanji: '本', en: 'Book', morae: 2, pos: 'Noun' },
    { id: 'pen', kana: 'ぺん', romaji: 'pen', kanji: 'ペン', en: 'Pen', morae: 2, pos: 'Noun' },
    { id: 'kasa', kana: 'かさ', romaji: 'kasa', kanji: '傘', en: 'Umbrella', morae: 2, pos: 'Noun' },
    { id: 'kutsu', kana: 'くつ', romaji: 'kutsu', kanji: '靴', en: 'Shoes', morae: 2, pos: 'Noun' },
    { id: 'mizu', kana: 'みず', romaji: 'mizu', kanji: '水', en: 'Water', morae: 2, pos: 'Noun' },
    { id: 'ashi', kana: 'あし', romaji: 'ashi', kanji: '足', en: 'Foot / Leg', morae: 2, pos: 'Noun' },
    { id: 'kuchi', kana: 'くち', romaji: 'kuchi', kanji: '口', en: 'Mouth', morae: 2, pos: 'Noun' },
    { id: 'mimi', kana: 'みみ', romaji: 'mimi', kanji: '耳', en: 'Ear', morae: 2, pos: 'Noun' },
    { id: 'kubi', kana: 'くび', romaji: 'kubi', kanji: '首', en: 'Neck', morae: 2, pos: 'Noun' },
    { id: 'ude', kana: 'うで', romaji: 'ude', kanji: '腕', en: 'Arm', morae: 2, pos: 'Noun' },
    { id: 'hiza', kana: 'ひざ', romaji: 'hiza', kanji: '膝', en: 'Knee', morae: 2, pos: 'Noun' },
    { id: 'mune', kana: 'むね', romaji: 'mune', kanji: '胸', en: 'Chest', morae: 2, pos: 'Noun' },
    { id: 'koe', kana: 'こえ', romaji: 'koe', kanji: '声', en: 'Voice', morae: 2, pos: 'Noun' },
    { id: 'oto', kana: 'おと', romaji: 'oto', kanji: '音', en: 'Sound', morae: 2, pos: 'Noun' },
    { id: 'uta', kana: 'うた', romaji: 'uta', kanji: '歌', en: 'Song', morae: 2, pos: 'Noun' },
    { id: 'iro', kana: 'いろ', romaji: 'iro', kanji: '色', en: 'Color', morae: 2, pos: 'Noun' },
    { id: 'kumo', kana: 'くも', romaji: 'kumo', kanji: '雲', en: 'Cloud', morae: 2, pos: 'Noun' },
    { id: 'nami', kana: 'なみ', romaji: 'nami', kanji: '波', en: 'Wave', morae: 2, pos: 'Noun' },
    { id: 'ishi', kana: 'いし', romaji: 'ishi', kanji: '石', en: 'Stone', morae: 2, pos: 'Noun' },
    { id: 'mori', kana: 'もり', romaji: 'mori', kanji: '森', en: 'Forest', morae: 2, pos: 'Noun' },
    { id: 'take', kana: 'たけ', romaji: 'take', kanji: '竹', en: 'Bamboo', morae: 2, pos: 'Noun' },
    { id: 'kusa', kana: 'くさ', romaji: 'kusa', kanji: '草', en: 'Grass', morae: 2, pos: 'Noun' },
    { id: 'suna', kana: 'すな', romaji: 'suna', kanji: '砂', en: 'Sand', morae: 2, pos: 'Noun' },
    { id: 'kage', kana: 'かげ', romaji: 'kage', kanji: '影', en: 'Shadow', morae: 2, pos: 'Noun' },
    { id: 'yume', kana: 'ゆめ', romaji: 'yume', kanji: '夢', en: 'Dream', morae: 2, pos: 'Noun' },
    { id: 'koi', kana: 'こい', romaji: 'koi', kanji: '恋', en: 'Romantic love', morae: 2, pos: 'Noun' },
    { id: 'ai', kana: 'あい', romaji: 'ai', kanji: '愛', en: 'Love', morae: 2, pos: 'Noun' },
    { id: 'suki', kana: 'すき', romaji: 'suki', kanji: '好き', en: 'Like', morae: 2, pos: 'Noun' },
    { id: 'iki', kana: 'いき', romaji: 'iki', kanji: '息', en: 'Breath', morae: 2, pos: 'Noun' },
    { id: 'toki', kana: 'とき', romaji: 'toki', kanji: '時', en: 'Time', morae: 2, pos: 'Noun' },
    { id: 'asa', kana: 'あさ', romaji: 'asa', kanji: '朝', en: 'Morning', morae: 2, pos: 'Noun' },
    { id: 'yoru', kana: 'よる', romaji: 'yoru', kanji: '夜', en: 'Night', morae: 2, pos: 'Noun' },
    { id: 'hiru', kana: 'ひる', romaji: 'hiru', kanji: '昼', en: 'Daytime', morae: 2, pos: 'Noun' },
    { id: 'ima', kana: 'いま', romaji: 'ima', kanji: '今', en: 'Now', morae: 2, pos: 'Adverb' },
    { id: 'mae', kana: 'まえ', romaji: 'mae', kanji: '前', en: 'Before / Front', morae: 2, pos: 'Adverb' },
    { id: 'ato', kana: 'あと', romaji: 'ato', kanji: '後', en: 'After', morae: 2, pos: 'Adverb' },
    { id: 'naka', kana: 'なか', romaji: 'naka', kanji: '中', en: 'Inside', morae: 2, pos: 'Adverb' },
    { id: 'soto', kana: 'そと', romaji: 'soto', kanji: '外', en: 'Outside', morae: 2, pos: 'Adverb' },
    { id: 'ue', kana: 'うえ', romaji: 'ue', kanji: '上', en: 'Up', morae: 2, pos: 'Noun' },
    { id: 'shita', kana: 'した', romaji: 'shita', kanji: '下', en: 'Down', morae: 2, pos: 'Noun' },
    { id: 'yoko', kana: 'よこ', romaji: 'yoko', kanji: '横', en: 'Side', morae: 2, pos: 'Noun' },
    { id: 'saki', kana: 'さき', romaji: 'saki', kanji: '先', en: 'Ahead', morae: 2, pos: 'Noun' },
    { id: 'uchi', kana: 'うち', romaji: 'uchi', kanji: '内', en: 'Inside / Home', morae: 2, pos: 'Adverb' },
    { id: 'hashi', kana: 'はし', romaji: 'hashi', kanji: '橋 / 箸', en: 'Bridge / Chopsticks', morae: 2, pos: 'Noun' },
    { id: 'kado', kana: 'かど', romaji: 'kado', kanji: '角', en: 'Corner', morae: 2, pos: 'Noun' },
    { id: 'tana', kana: 'たな', romaji: 'tana', kanji: '棚', en: 'Shelf', morae: 2, pos: 'Noun' },
    { id: 'kabe', kana: 'かべ', romaji: 'kabe', kanji: '壁', en: 'Wall', morae: 2, pos: 'Noun' },
    { id: 'mado', kana: 'まど', romaji: 'mado', kanji: '窓', en: 'Window', morae: 2, pos: 'Noun' },
    { id: 'isu', kana: 'いす', romaji: 'isu', kanji: '椅子', en: 'Chair', morae: 2, pos: 'Noun' },
    { id: 'fune', kana: 'ふね', romaji: 'fune', kanji: '船', en: 'Boat', morae: 2, pos: 'Noun' },
    { id: 'kome', kana: 'こめ', romaji: 'kome', kanji: '米', en: 'Rice', morae: 2, pos: 'Noun' },
    { id: 'miso', kana: 'みそ', romaji: 'miso', kanji: '味噌', en: 'Miso', morae: 2, pos: 'Noun' },
    { id: 'sushi', kana: 'すし', romaji: 'sushi', kanji: '寿司', en: 'Sushi', morae: 2, pos: 'Noun' },
    { id: 'niku', kana: 'にく', romaji: 'niku', kanji: '肉', en: 'Meat', morae: 2, pos: 'Noun' },
    { id: 'nori', kana: 'のり', romaji: 'nori', kanji: '海苔', en: 'Seaweed', morae: 2, pos: 'Noun' },
    { id: 'taki', kana: 'たき', romaji: 'taki', kanji: '滝', en: 'Waterfall', morae: 2, pos: 'Noun' },
    { id: 'shima', kana: 'しま', romaji: 'shima', kanji: '島', en: 'Island', morae: 2, pos: 'Noun' },
    { id: 'kuni', kana: 'くに', romaji: 'kuni', kanji: '国', en: 'Country', morae: 2, pos: 'Noun' },
    { id: 'sato', kana: 'さと', romaji: 'sato', kanji: '里', en: 'Village / Hometown', morae: 2, pos: 'Noun' },
    { id: 'mura', kana: 'むら', romaji: 'mura', kanji: '村', en: 'Village', morae: 2, pos: 'Noun' },
    { id: 'shiro', kana: 'しろ', romaji: 'shiro', kanji: '白', en: 'White', morae: 2, pos: 'Noun' },
    { id: 'kuro', kana: 'くろ', romaji: 'kuro', kanji: '黒', en: 'Black', morae: 2, pos: 'Noun' },
    { id: 'aka', kana: 'あか', romaji: 'aka', kanji: '赤', en: 'Red', morae: 2, pos: 'Noun' },
    { id: 'ao', kana: 'あお', romaji: 'ao', kanji: '青', en: 'Blue', morae: 2, pos: 'Noun' },
    { id: 'kako', kana: 'かこ', romaji: 'kako', kanji: '過去', en: 'Past', morae: 2, pos: 'Noun' },
    { id: 'kiri', kana: 'きり', romaji: 'kiri', kanji: '霧', en: 'Fog', morae: 2, pos: 'Noun' },
    { id: 'tsuki', kana: 'つき', romaji: 'tsuki', kanji: '月', en: 'Moon', morae: 2, pos: 'Noun' },
    { id: 'hoshi', kana: 'ほし', romaji: 'hoshi', kanji: '星', en: 'Star', morae: 2, pos: 'Noun' },
    { id: 'kishi', kana: 'きし', romaji: 'kishi', kanji: '岸', en: 'Shore', morae: 2, pos: 'Noun' },
    { id: 'kami', kana: 'かみ', romaji: 'kami', kanji: '紙 / 髪 / 神', en: 'Paper / Hair / God', morae: 2, pos: 'Noun' },
    { id: 'pan', kana: 'パン', romaji: 'pan', kanji: 'パン', en: 'Bread', morae: 2, pos: 'Noun' },
    { id: 'jisho', kana: 'じしょ', romaji: 'jisho', kanji: '辞書', en: 'Dictionary', morae: 2, pos: 'Noun' },
    { id: 'sugu', kana: 'すぐ', romaji: 'sugu', kanji: '直ぐ', en: 'Immediately', morae: 2, pos: 'Adverb' },
    { id: 'mada', kana: 'まだ', romaji: 'mada', kanji: 'まだ', en: 'Not yet', morae: 2, pos: 'Adverb' },
    { id: 'miru', kana: 'みる', romaji: 'miru', kanji: '見る', en: 'To see', morae: 2, pos: 'Verb' },
    { id: 'iku', kana: 'いく', romaji: 'iku', kanji: '行く', en: 'To go', morae: 2, pos: 'Verb' },
    { id: 'kuru', kana: 'くる', romaji: 'kuru', kanji: '来る', en: 'To come', morae: 2, pos: 'Verb' },
    { id: 'nomu', kana: 'のむ', romaji: 'nomu', kanji: '飲む', en: 'To drink', morae: 2, pos: 'Verb' },
    { id: 'neru', kana: 'ねる', romaji: 'neru', kanji: '寝る', en: 'To sleep', morae: 2, pos: 'Verb' },
    { id: 'kiku', kana: 'きく', romaji: 'kiku', kanji: '聞く', en: 'To listen / ask', morae: 2, pos: 'Verb' },
    { id: 'kau', kana: 'かう', romaji: 'kau', kanji: '買う', en: 'To buy', morae: 2, pos: 'Verb' },
    { id: 'matsu', kana: 'まつ', romaji: 'matsu', kanji: '待つ', en: 'To wait', morae: 2, pos: 'Verb' },
    { id: 'au', kana: 'あう', romaji: 'au', kanji: '会う', en: 'To meet', morae: 2, pos: 'Verb' },
    { id: 'shiru', kana: 'しる', romaji: 'shiru', kanji: '知る', en: 'To know', morae: 2, pos: 'Verb' },
    { id: 'naku', kana: 'なく', romaji: 'naku', kanji: '泣く', en: 'To cry', morae: 2, pos: 'Verb' },
    { id: 'kiru', kana: 'きる', romaji: 'kiru', kanji: '切る', en: 'To cut', morae: 2, pos: 'Verb' },
    { id: 'kiru', kana: 'きる', romaji: 'kiru', kanji: '着る', en: 'To wear', morae: 2, pos: 'Verb' },
    { id: 'dasu', kana: 'だす', romaji: 'dasu', kanji: '出す', en: 'To take out', morae: 2, pos: 'Verb' },
    { id: 'deru', kana: 'でる', romaji: 'deru', kanji: '出る', en: 'To exit', morae: 2, pos: 'Verb' },
    { id: 'tatsu', kana: 'たつ', romaji: 'tatsu', kanji: '立つ', en: 'To stand', morae: 2, pos: 'Verb' },
    { id: 'kaku', kana: 'かく', romaji: 'kaku', kanji: '書く', en: 'To write', morae: 2, pos: 'Verb' },
    { id: 'yomu', kana: 'よむ', romaji: 'yomu', kanji: '読む', en: 'To read', morae: 2, pos: 'Verb' },
    { id: 'noru', kana: 'のる', romaji: 'noru', kanji: '乗る', en: 'To ride', morae: 2, pos: 'Verb' },
    { id: 'shinu', kana: 'しぬ', romaji: 'shinu', kanji: '死ぬ', en: 'To die', morae: 2, pos: 'Verb' },
    { id: 'yobu', kana: 'よぶ', romaji: 'yobu', kanji: '呼ぶ', en: 'To call', morae: 2, pos: 'Verb' },
    { id: 'uso', kana: 'うそ', romaji: 'uso', kanji: '嘘', en: 'Lie', morae: 2, pos: 'Noun' },
    { id: 'itsu', kana: 'いつ', romaji: 'itsu', kanji: 'いつ', en: 'When', morae: 2, pos: 'Other' },
    { id: 'doko', kana: 'どこ', romaji: 'doko', kanji: 'どこ', en: 'Where', morae: 2, pos: 'Other' },
    { id: 'dare', kana: 'だれ', romaji: 'dare', kanji: '誰', en: 'Who', morae: 2, pos: 'Other' },
    { id: 'nani', kana: 'なに', romaji: 'nani', kanji: '何', en: 'What', morae: 2, pos: 'Other' },
    { id: 'naze', kana: 'なぜ', romaji: 'naze', kanji: '何故', en: 'Why', morae: 2, pos: 'Other' },
    { id: 'mou', kana: 'もう', romaji: 'mou', kanji: 'もう', en: 'Already / More', morae: 2, pos: 'Adjective' },
    // 3 Morae
    { id: 'inochi', kana: 'いのち', romaji: 'inochi', kanji: '命', en: 'Life', morae: 3, pos: 'Noun' },
    { id: 'genki', kana: 'げんき', romaji: 'genki', kanji: '元気', en: 'Healthy / Energetic', morae: 3, pos: 'Adjective' },
    { id: 'mirai', kana: 'みらい', romaji: 'mirai', kanji: '未来', en: 'Future', morae: 3, pos: 'Noun' },
    { id: 'chikara', kana: 'ちから', romaji: 'chikara', kanji: '力', en: 'Power', morae: 3, pos: 'Noun' },
    { id: 'kokoro', kana: 'こころ', romaji: 'kokoro', kanji: '心', en: 'Heart / Mind', morae: 3, pos: 'Noun' },
    { id: 'sakura', kana: 'さくら', romaji: 'sakura', kanji: '桜', en: 'Cherry Blossom', morae: 3, pos: 'Noun' },
    { id: 'kuruma', kana: 'くるま', romaji: 'kuruma', kanji: '車', en: 'Car', morae: 3, pos: 'Noun' },
    { id: 'denwa', kana: 'でんわ', romaji: 'denwa', kanji: '電話', en: 'Phone', morae: 3, pos: 'Noun' },
    { id: 'tokei', kana: 'とけい', romaji: 'tokei', kanji: '時計', en: 'Clock', morae: 3, pos: 'Noun' },
    { id: 'megane', kana: 'めがね', romaji: 'megane', kanji: '眼鏡', en: 'Glasses', morae: 3, pos: 'Noun' },
    { id: 'kamera', kana: 'カメラ', romaji: 'kamera', kanji: 'カメラ', en: 'Camera', morae: 3, pos: 'Noun' },
    { id: 'terebi', kana: 'テレビ', romaji: 'terebi', kanji: 'テレビ', en: 'TV', morae: 3, pos: 'Noun' },
    { id: 'rajio', kana: 'ラジオ', romaji: 'rajio', kanji: 'ラジオ', en: 'Radio', morae: 3, pos: 'Noun' },
    { id: 'fukuro', kana: 'ふくろ', romaji: 'fukuro', kanji: '袋', en: 'Bag', morae: 3, pos: 'Noun' },
    { id: 'saifu', kana: 'さいふ', romaji: 'saifu', kanji: '財布', en: 'Wallet', morae: 3, pos: 'Noun' },
    { id: 'osara', kana: 'おさら', romaji: 'osara', kanji: 'お皿', en: 'Plate', morae: 3, pos: 'Noun' },
    { id: 'nihon', kana: 'にほん', romaji: 'nihon', kanji: '日本', en: 'Japan', morae: 3, pos: 'Noun' },
    { id: 'sekai', kana: 'せかい', romaji: 'sekai', kanji: '世界', en: 'World', morae: 3, pos: 'Noun' },
    { id: 'kodomo', kana: 'こども', romaji: 'kodomo', kanji: '子供', en: 'Child', morae: 3, pos: 'Noun' },
    { id: 'otona', kana: 'おとな', romaji: 'otona', kanji: '大人', en: 'Adult', morae: 3, pos: 'Noun' },
    { id: 'kodomo', kana: 'こども', romaji: 'kodomo', kanji: '子供', en: 'Child', morae: 3, pos: 'Noun' },
    { id: 'kuruma', kana: 'くるま', romaji: 'kuruma', kanji: '車', en: 'Car', morae: 3, pos: 'Noun' },
    { id: 'kazoku', kana: 'かぞく', romaji: 'kazoku', kanji: '家族', en: 'Family', morae: 3, pos: 'Noun' },
    { id: 'otoko', kana: 'おとこ', romaji: 'otoko', kanji: '男', en: 'Man', morae: 3, pos: 'Noun' },
    { id: 'onna', kana: 'おんな', romaji: 'onna', kanji: '女', en: 'Woman', morae: 3, pos: 'Noun' },
    { id: 'kanojo', kana: 'かのじょ', romaji: 'kanojo', kanji: '彼女', en: 'She / Girlfriend', morae: 3, pos: 'Other' },
    { id: 'atama', kana: 'あたま', romaji: 'atama', kanji: '頭', en: 'Head', morae: 3, pos: 'Noun' },
    { id: 'karada', kana: 'からだ', romaji: 'karada', kanji: '体', en: 'Body', morae: 3, pos: 'Noun' },
    { id: 'senaka', kana: 'せなか', romaji: 'senaka', kanji: '背中', en: 'Back', morae: 3, pos: 'Noun' },
    { id: 'kokoro', kana: 'こころ', romaji: 'kokoro', kanji: '心', en: 'Heart / Mind', morae: 3, pos: 'Noun' },
    { id: 'inochi', kana: 'いのち', romaji: 'inochi', kanji: '命', en: 'Life', morae: 3, pos: 'Noun' },
    { id: 'tamago', kana: 'たまご', romaji: 'tamago', kanji: '卵', en: 'Egg', morae: 3, pos: 'Noun' },
    { id: 'sakana', kana: 'さかな', romaji: 'sakana', kanji: '魚', en: 'Fish', morae: 3, pos: 'Noun' },
    { id: 'yasai', kana: 'やさい', romaji: 'yasai', kanji: '野菜', en: 'Vegetables', morae: 3, pos: 'Noun' },
    { id: 'banana', kana: 'バナナ', romaji: 'banana', kanji: 'バナナ', en: 'Banana', morae: 3, pos: 'Noun' },
    { id: 'ringo', kana: 'りんご', romaji: 'ringo', kanji: '林檎', en: 'Apple', morae: 3, pos: 'Noun' },
    { id: 'ichigo', kana: 'いちご', romaji: 'ichigo', kanji: '苺', en: 'Strawberry', morae: 3, pos: 'Noun' },
    { id: 'miruku', kana: 'ミルク', romaji: 'miruku', kanji: 'ミルク', en: 'Milk', morae: 3, pos: 'Noun' },
    { id: 'tabako', kana: 'たばこ', romaji: 'tabako', kanji: '煙草', en: 'Cigarette', morae: 3, pos: 'Noun' },
    { id: 'terebi', kana: 'テレビ', romaji: 'terebi', kanji: 'テレビ', en: 'TV', morae: 3, pos: 'Noun' },
    { id: 'kamera', kana: 'カメラ', romaji: 'kamera', kanji: 'カメラ', en: 'Camera', morae: 3, pos: 'Noun' },
    { id: 'denwa', kana: 'でんわ', romaji: 'denwa', kanji: '電話', en: 'Phone', morae: 3, pos: 'Noun' },
    { id: 'kippu', kana: 'きっぷ', romaji: 'kippu', kanji: '切符', en: 'Ticket', morae: 3, pos: 'Noun' },
    { id: 'ryokou', kana: 'りょこう', romaji: 'ryokou', kanji: '旅行', en: 'Travel', morae: 3, pos: 'Noun' },
    { id: 'kaisha', kana: 'かいしゃ', romaji: 'kaisha', kanji: '会社', en: 'Company', morae: 3, pos: 'Noun' },
    { id: 'shigoto', kana: 'しごと', romaji: 'shigoto', kanji: '仕事', en: 'Work', morae: 3, pos: 'Noun' },
    { id: 'yasumi', kana: 'やすみ', romaji: 'yasumi', kanji: '休み', en: 'Rest / Holiday', morae: 3, pos: 'Noun' },
    { id: 'asobi', kana: 'あそび', romaji: 'asobi', kanji: '遊び', en: 'Play', morae: 3, pos: 'Noun' },
    { id: 'hanashi', kana: 'はなし', romaji: 'hanashi', kanji: '話', en: 'Story / Talk', morae: 3, pos: 'Noun' },
    { id: 'omise', kana: 'おみせ', romaji: 'omise', kanji: 'お店', en: 'Shop', morae: 3, pos: 'Noun' },
    { id: 'ryouri', kana: 'りょうり', romaji: 'ryouri', kanji: '料理', en: 'Cooking / Food', morae: 3, pos: 'Noun' },
    { id: 'ofuro', kana: 'おふろ', romaji: 'ofuro', kanji: 'お風呂', en: 'Bath', morae: 3, pos: 'Noun' },
    { id: 'kibun', kana: 'きぶん', romaji: 'kibun', kanji: '気分', en: 'Mood', morae: 3, pos: 'Noun' },
    { id: 'nemuri', kana: 'ねむり', romaji: 'nemuri', kanji: '眠り', en: 'Sleep', morae: 3, pos: 'Noun' },
    { id: 'okane', kana: 'おかね', romaji: 'okane', kanji: 'お金', en: 'Money', morae: 3, pos: 'Noun' },
    { id: 'tegami', kana: 'てがみ', romaji: 'tegami', kanji: '手紙', en: 'Letter', morae: 3, pos: 'Noun' },
    { id: 'shashin', kana: 'しゃしん', romaji: 'shashin', kanji: '写真', en: 'Photo', morae: 3, pos: 'Noun' },
    { id: 'hikaru', kana: 'ひかる', romaji: 'hikaru', kanji: '光る', en: 'To shine', morae: 3, pos: 'Verb' },
    { id: 'warai', kana: 'わらい', romaji: 'warai', kanji: '笑い', en: 'Laugh', morae: 3, pos: 'Noun' },
    { id: 'kowai', kana: 'こわい', romaji: 'kowai', kanji: '怖い', en: 'Scary', morae: 3, pos: 'Noun' },
    { id: 'atsui', kana: 'あつい', romaji: 'atsui', kanji: '暑い / 熱い', en: 'Hot', morae: 3, pos: 'Adjective' },
    { id: 'samui', kana: 'さむい', romaji: 'samui', kanji: '寒い', en: 'Cold', morae: 3, pos: 'Adjective' },
    { id: 'hayai', kana: 'はやい', romaji: 'hayai', kanji: '早い / 速い', en: 'Fast / Early', morae: 3, pos: 'Adjective' },
    { id: 'osoi', kana: 'おそい', romaji: 'osoi', kanji: '遅い', en: 'Slow / Late', morae: 3, pos: 'Adjective' },
    { id: 'takai', kana: 'たかい', romaji: 'takai', kanji: '高い', en: 'High / Expensive', morae: 3, pos: 'Adjective' },
    { id: 'yasui', kana: 'やすい', romaji: 'yasui', kanji: '安い', en: 'Cheap', morae: 3, pos: 'Adjective' },
    { id: 'furui', kana: 'ふるい', romaji: 'furui', kanji: '古い', en: 'Old', morae: 3, pos: 'Adjective' },
    { id: 'kirei', kana: 'きれい', romaji: 'kirei', kanji: '綺麗', en: 'Pretty / Clean', morae: 3, pos: 'Adjective' },
    { id: 'shizuka', kana: 'しずか', romaji: 'shizuka', kanji: '静か', en: 'Quiet', morae: 3, pos: 'Adjective' },
    { id: 'benri', kana: 'べんり', romaji: 'benri', kanji: '便利', en: 'Convenient', morae: 3, pos: 'Adjective' },
    { id: 'daiji', kana: 'だいじ', romaji: 'daiji', kanji: '大事', en: 'Important', morae: 3, pos: 'Adjective' },
    { id: 'kiken', kana: 'きけん', romaji: 'kiken', kanji: '危険', en: 'Danger', morae: 3, pos: 'Noun' },
    { id: 'jiyuu', kana: 'じゆう', romaji: 'jiyuu', kanji: '自由', en: 'Freedom', morae: 3, pos: 'Noun' },
    { id: 'heiwa', kana: 'へいわ', romaji: 'heiwa', kanji: '平和', en: 'Peace', morae: 3, pos: 'Noun' },
    { id: 'kibou', kana: 'きぼう', romaji: 'kibou', kanji: '希望', en: 'Hope', morae: 3, pos: 'Noun' },
    { id: 'hajime', kana: 'はじめ', romaji: 'hajime', kanji: '始め', en: 'Beginning', morae: 3, pos: 'Noun' },
    { id: 'owari', kana: 'おわり', romaji: 'owari', kanji: '終わり', en: 'End', morae: 3, pos: 'Noun' },
    { id: 'mukashi', kana: 'むかし', romaji: 'mukashi', kanji: '昔', en: 'Long ago', morae: 3, pos: 'Adjective' },
    { id: 'itsumo', kana: 'いつも', romaji: 'itsumo', kanji: 'いつも', en: 'Always', morae: 3, pos: 'Adverb' },
    { id: 'sukoshi', kana: 'すこし', romaji: 'sukoshi', kanji: '少し', en: 'A little', morae: 3, pos: 'Adjective' },
    { id: 'minna', kana: 'みんな', romaji: 'minna', kanji: '皆', en: 'Everyone', morae: 3, pos: 'Noun' },
    { id: 'zutto', kana: 'ずっと', romaji: 'zutto', kanji: 'ずっと', en: 'Always / Long time', morae: 3, pos: 'Adverb' },
    { id: 'kitto', kana: 'きっと', romaji: 'kitto', kanji: 'きっと', en: 'Surely', morae: 3, pos: 'Noun' },
    { id: 'yatto', kana: 'やっと', romaji: 'yatto', kanji: 'やっと', en: 'Finally', morae: 3, pos: 'Adverb' },
    { id: 'motto', kana: 'もっと', romaji: 'motto', kanji: 'もっと', en: 'More', morae: 3, pos: 'Adjective' },
    { id: 'zenbu', kana: 'ぜんぶ', romaji: 'zenbu', kanji: '全部', en: 'All', morae: 3, pos: 'Adjective' },
    { id: 'chanto', kana: 'ちゃんと', romaji: 'chanto', kanji: 'ちゃんと', en: 'Properly', morae: 3, pos: 'Noun' },
    { id: 'tabun', kana: 'たぶん', romaji: 'tabun', kanji: '多分', en: 'Probably', morae: 3, pos: 'Other' },
    { id: 'sugoi', kana: 'すごい', romaji: 'sugoi', kanji: '凄い', en: 'Amazing', morae: 3, pos: 'Adjective' },
    { id: 'yabai', kana: 'やばい', romaji: 'yabai', kanji: 'ヤバい', en: 'Awesome / Dangerous', morae: 3, pos: 'Adjective' },
    { id: 'muzui', kana: 'むずい', romaji: 'muzui', kanji: '難い', en: 'Hard (slang)', morae: 3, pos: 'Adjective' },
    { id: 'nemui', kana: 'ねむい', romaji: 'nemui', kanji: '眠い', en: 'Sleepy', morae: 3, pos: 'Adjective' },
    { id: 'itai', kana: 'いたい', romaji: 'itai', kanji: '痛い', en: 'Painful', morae: 3, pos: 'Noun' },
    { id: 'ureshi', kana: 'うれし', romaji: 'ureshi', kanji: '嬉し', en: 'Happy (stem)', morae: 3, pos: 'Adjective' },
    { id: 'kanashi', kana: 'かなし', romaji: 'kanashi', kanji: '悲し', en: 'Sad (stem)', morae: 3, pos: 'Adjective' },
    { id: 'ikiru', kana: 'いきる', romaji: 'ikiru', kanji: '生きる', en: 'To live', morae: 3, pos: 'Verb' },
    { id: 'taberu', kana: 'たべる', romaji: 'taberu', kanji: '食べる', en: 'To eat', morae: 3, pos: 'Verb' },
    { id: 'okiru', kana: 'おきる', romaji: 'okiru', kanji: '起きる', en: 'To wake up', morae: 3, pos: 'Verb' },
    { id: 'aruku', kana: 'あるく', romaji: 'aruku', kanji: '歩く', en: 'To walk', morae: 3, pos: 'Verb' },
    { id: 'hashiru', kana: 'はしる', romaji: 'hashiru', kanji: '走る', en: 'To run', morae: 3, pos: 'Verb' },
    { id: 'asobu', kana: 'あそぶ', romaji: 'asobu', kanji: '遊ぶ', en: 'To play', morae: 3, pos: 'Verb' },
    { id: 'hanasu', kana: 'はなす', romaji: 'hanasu', kanji: '話す', en: 'To speak', morae: 3, pos: 'Verb' },
    { id: 'wakaru', kana: 'わかる', romaji: 'wakaru', kanji: '分かる', en: 'To understand', morae: 3, pos: 'Verb' },
    { id: 'tsukuru', kana: 'つくる', romaji: 'tsukuru', kanji: '作る', en: 'To make', morae: 3, pos: 'Verb' },
    { id: 'warau', kana: 'わらう', romaji: 'warau', kanji: '笑う', en: 'To laugh', morae: 3, pos: 'Verb' },
    { id: 'omou', kana: 'おもう', romaji: 'omou', kanji: '思う', en: 'To think', morae: 3, pos: 'Verb' },
    { id: 'aeru', kana: 'あえる', romaji: 'aeru', kanji: '会える', en: 'Can meet', morae: 3, pos: 'Noun' },
    { id: 'mirai3', kana: 'みらい', romaji: 'mirai', kanji: '未来', en: 'Future', morae: 3, pos: 'Noun' },
    { id: 'negai', kana: 'ねがい', romaji: 'negai', kanji: '願い', en: 'Wish', morae: 3, pos: 'Noun' },
    { id: 'kimochi', kana: 'きもち', romaji: 'kimochi', kanji: '気持ち', en: 'Feeling', morae: 3, pos: 'Noun' },
    { id: 'himitsu', kana: 'ひみつ', romaji: 'himitsu', kanji: '秘密', en: 'Secret', morae: 3, pos: 'Noun' },
    { id: 'chikai', kana: 'ちかい', romaji: 'chikai', kanji: '近い', en: 'Near', morae: 3, pos: 'Adjective' },
    { id: 'tooi', kana: 'とおい', romaji: 'tooi', kanji: '遠い', en: 'Far', morae: 3, pos: 'Adjective' },
    { id: 'katai', kana: 'かたい', romaji: 'katai', kanji: '硬い', en: 'Hard', morae: 3, pos: 'Adjective' },
    { id: 'amai', kana: 'あまい', romaji: 'amai', kanji: '甘い', en: 'Sweet', morae: 3, pos: 'Adjective' },
    { id: 'karai', kana: 'からい', romaji: 'karai', kanji: '辛い', en: 'Spicy / Painful', morae: 3, pos: 'Adjective' },
    { id: 'nigai', kana: 'にがい', romaji: 'nigai', kanji: '苦い', en: 'Bitter', morae: 3, pos: 'Adjective' },
    { id: 'umai', kana: 'うまい', romaji: 'umai', kanji: '旨い / 上手い', en: 'Tasty / Skillful', morae: 3, pos: 'Adjective' },
    { id: 'warui', kana: 'わるい', romaji: 'warui', kanji: '悪い', en: 'Bad', morae: 3, pos: 'Adjective' },
    { id: 'yowai', kana: 'よわい', romaji: 'yowai', kanji: '弱い', en: 'Weak', morae: 3, pos: 'Adjective' },
    { id: 'tsuyoi', kana: 'つよい', romaji: 'tsuyoi', kanji: '強い', en: 'Strong', morae: 3, pos: 'Adjective' },
    { id: 'atsui2', kana: 'あつい', romaji: 'atsui', kanji: '厚い', en: 'Thick', morae: 3, pos: 'Adjective' },
    { id: 'usui', kana: 'うすい', romaji: 'usui', kanji: '薄い', en: 'Thin', morae: 3, pos: 'Adjective' },
    { id: 'owaru', kana: 'おわる', romaji: 'owaru', kanji: '終わる', en: 'To end', morae: 3, pos: 'Verb' },
    { id: 'mukau', kana: 'むかう', romaji: 'mukau', kanji: '向かう', en: 'To head toward', morae: 3, pos: 'Verb' },
    { id: 'tsuzuku', kana: 'つづく', romaji: 'tsuzuku', kanji: '続く', en: 'To continue', morae: 3, pos: 'Verb' },
    { id: 'erabu', kana: 'えらぶ', romaji: 'erabu', kanji: '選ぶ', en: 'To choose', morae: 3, pos: 'Verb' },
    { id: 'mamoru', kana: 'まもる', romaji: 'mamoru', kanji: '守る', en: 'To protect', morae: 3, pos: 'Verb' },
    { id: 'kaeru', kana: 'かえる', romaji: 'kaeru', kanji: '帰る', en: 'To return', morae: 3, pos: 'Verb' },
    { id: 'hajiku', kana: 'はじく', romaji: 'hajiku', kanji: '弾く', en: 'To play (instrument)', morae: 3, pos: 'Verb' },
    { id: 'akeru', kana: 'あける', romaji: 'akeru', kanji: '開ける', en: 'To open', morae: 3, pos: 'Verb' },
    { id: 'tojiru', kana: 'とじる', romaji: 'tojiru', kanji: '閉じる', en: 'To close', morae: 3, pos: 'Verb' },
    { id: 'noboru', kana: 'のぼる', romaji: 'noboru', kanji: '登る', en: 'To climb', morae: 3, pos: 'Verb' },
    { id: 'oriru', kana: 'おりる', romaji: 'oriru', kanji: '降りる', en: 'To get off', morae: 3, pos: 'Verb' },
    { id: 'tsukau', kana: 'つかう', romaji: 'tsukau', kanji: '使う', en: 'To use', morae: 3, pos: 'Verb' },
    { id: 'arau', kana: 'あらう', romaji: 'arau', kanji: '洗う', en: 'To wash', morae: 3, pos: 'Verb' },
    { id: 'ageru', kana: 'あげる', romaji: 'ageru', kanji: '上げる', en: 'To raise / give', morae: 3, pos: 'Verb' },
    { id: 'kureru', kana: 'くれる', romaji: 'kureru', kanji: 'くれる', en: 'To give (to me)', morae: 3, pos: 'Verb' },
    { id: 'morau', kana: 'もらう', romaji: 'morau', kanji: '貰う', en: 'To receive', morae: 3, pos: 'Verb' },
    { id: 'tsukuru2', kana: 'つくる', romaji: 'tsukuru', kanji: '作る', en: 'To make', morae: 3, pos: 'Verb' },
    { id: 'kimeru', kana: 'きめる', romaji: 'kimeru', kanji: '決める', en: 'To decide', morae: 3, pos: 'Verb' },
    { id: 'shimeru', kana: 'しめる', romaji: 'shimeru', kanji: '閉める', en: 'To close (transitive)', morae: 3, pos: 'Verb' },
    { id: 'akaru', kana: 'あかる', romaji: 'akaru', kanji: '明る', en: 'Bright (stem)', morae: 3, pos: 'Adjective' },
    { id: 'kurai', kana: 'くらい', romaji: 'kurai', kanji: '暗い', en: 'Dark', morae: 3, pos: 'Adjective' },
    { id: 'wakai', kana: 'わかい', romaji: 'wakai', kanji: '若い', en: 'Young', morae: 3, pos: 'Adjective' },
    { id: 'fukai', kana: 'ふかい', romaji: 'fukai', kanji: '深い', en: 'Deep', morae: 3, pos: 'Adjective' },
    { id: 'asai', kana: 'あさい', romaji: 'asai', kanji: '浅い', en: 'Shallow', morae: 3, pos: 'Adjective' },
    { id: 'nagai', kana: 'ながい', romaji: 'nagai', kanji: '長い', en: 'Long', morae: 3, pos: 'Adjective' },
    { id: 'ataru', kana: 'あたる', romaji: 'ataru', kanji: '当たる', en: 'To hit / win', morae: 3, pos: 'Verb' },
    { id: 'nokoru', kana: 'のこる', romaji: 'nokoru', kanji: '残る', en: 'To remain', morae: 3, pos: 'Verb' },
    { id: 'kaesu', kana: 'かえす', romaji: 'kaesu', kanji: '返す', en: 'To return (something)', morae: 3, pos: 'Verb' },
    { id: 'ireru', kana: 'いれる', romaji: 'ireru', kanji: '入れる', en: 'To put in', morae: 3, pos: 'Verb' },
    { id: 'hairu', kana: 'はいる', romaji: 'hairu', kanji: '入る', en: 'To enter', morae: 3, pos: 'Verb' },
    { id: 'akeru2', kana: 'あける', romaji: 'akeru', kanji: '明ける', en: 'To dawn / open', morae: 3, pos: 'Verb' },
    { id: 'ochiru', kana: 'おちる', romaji: 'ochiru', kanji: '落ちる', en: 'To fall', morae: 3, pos: 'Verb' },
    { id: 'ageru2', kana: 'あげる', romaji: 'ageru', kanji: '揚げる', en: 'To fry', morae: 3, pos: 'Verb' },
    { id: 'yureru', kana: 'ゆれる', romaji: 'yureru', kanji: '揺れる', en: 'To shake', morae: 3, pos: 'Verb' },
    { id: 'kawaru', kana: 'かわる', romaji: 'kawaru', kanji: '変わる', en: 'To change', morae: 3, pos: 'Verb' },
    { id: 'suwaru', kana: 'すわる', romaji: 'suwaru', kanji: '座る', en: 'To sit', morae: 3, pos: 'Verb' },
    { id: 'homeru', kana: 'ほめる', romaji: 'homeru', kanji: '褒める', en: 'To praise', morae: 3, pos: 'Verb' },
    { id: 'shikar', kana: 'しかる', romaji: 'shikaru', kanji: '叱る', en: 'To scold', morae: 3, pos: 'Verb' },
    { id: 'sukuu', kana: 'すくう', romaji: 'sukuu', kanji: '救う', en: 'To save', morae: 3, pos: 'Verb' },
    { id: 'meguru', kana: 'めぐる', romaji: 'meguru', kanji: '巡る', en: 'To go around', morae: 3, pos: 'Verb' },
    { id: 'kawasu', kana: 'かわす', romaji: 'kawasu', kanji: '交わす', en: 'To exchange', morae: 3, pos: 'Verb' },
    { id: 'nureru', kana: 'ぬれる', romaji: 'nureru', kanji: '濡れる', en: 'To get wet', morae: 3, pos: 'Verb' },
    { id: 'tozasu', kana: 'とざす', romaji: 'tozasu', kanji: '閉ざす', en: 'To shut', morae: 3, pos: 'Verb' },
    { id: 'hiraku', kana: 'ひらく', romaji: 'hiraku', kanji: '開く', en: 'To open', morae: 3, pos: 'Verb' },
    { id: 'ikiru2', kana: 'いきる', romaji: 'ikiru', kanji: '生きる', en: 'To live', morae: 3, pos: 'Verb' },
    { id: 'todoku', kana: 'とどく', romaji: 'todoku', kanji: '届く', en: 'To arrive', morae: 3, pos: 'Verb' },
    { id: 'ukeru', kana: 'うける', romaji: 'ukeru', kanji: '受ける', en: 'To receive', morae: 3, pos: 'Verb' },
    { id: 'suteru', kana: 'すてる', romaji: 'suteru', kanji: '捨てる', en: 'To throw away', morae: 3, pos: 'Verb' },
    { id: 'hirou', kana: 'ひろう', romaji: 'hirou', kanji: '拾う', en: 'To pick up', morae: 3, pos: 'Verb' },
    { id: 'megumu', kana: 'めぐむ', romaji: 'megumu', kanji: '恵む', en: 'To bless / give', morae: 3, pos: 'Verb' },
    { id: 'shizumu', kana: 'しずむ', romaji: 'shizumu', kanji: '沈む', en: 'To sink', morae: 3, pos: 'Verb' },
    { id: 'ukabu', kana: 'うかぶ', romaji: 'ukabu', kanji: '浮かぶ', en: 'To float', morae: 3, pos: 'Verb' },
    { id: 'mukeru', kana: 'むける', romaji: 'mukeru', kanji: '向ける', en: 'To turn toward', morae: 3, pos: 'Verb' },
    { id: 'kireru', kana: 'きれる', romaji: 'kireru', kanji: '切れる', en: 'To snap / cut', morae: 3, pos: 'Verb' },
    { id: 'nageru', kana: 'なげる', romaji: 'nageru', kanji: '投げる', en: 'To throw', morae: 3, pos: 'Verb' },
    { id: 'mieru', kana: 'みえる', romaji: 'mieru', kanji: '見える', en: 'To be visible', morae: 3, pos: 'Verb' },
    { id: 'dekiru', kana: 'できる', romaji: 'dekiru', kanji: '出来る', en: 'Can do', morae: 3, pos: 'Noun' },
    { id: 'kanau', kana: 'かなう', romaji: 'kanau', kanji: '叶う', en: 'To come true', morae: 3, pos: 'Verb' },
    { id: 'negau', kana: 'ねがう', romaji: 'negau', kanji: '願う', en: 'To wish', morae: 3, pos: 'Verb' },
    { id: 'yurusu', kana: 'ゆるす', romaji: 'yurusu', kanji: '許す', en: 'To forgive', morae: 3, pos: 'Verb' },
    { id: 'kizuku', kana: 'きづく', romaji: 'kizuku', kanji: '気づく', en: 'To notice', morae: 3, pos: 'Verb' },
    { id: 'jibun', kana: 'じぶん', romaji: 'jibun', kanji: '自分', en: 'Oneself', morae: 3, pos: 'Noun' },
    { id: 'aitsu', kana: 'あいつ', romaji: 'aitsu', kanji: 'あいつ', en: 'That guy (casual)', morae: 3, pos: 'Other' },
    { id: 'koitsu', kana: 'こいつ', romaji: 'koitsu', kanji: 'こいつ', en: 'This guy', morae: 3, pos: 'Other' },
    { id: 'soitsu', kana: 'そいつ', romaji: 'soitsu', kanji: 'そいつ', en: 'That guy', morae: 3, pos: 'Other' },
    { id: 'donna', kana: 'どんな', romaji: 'donna', kanji: 'どんな', en: 'What kind', morae: 3, pos: 'Adjective' },
    { id: 'nande', kana: 'なんで', romaji: 'nande', kanji: '何で', en: 'Why (casual)', morae: 3, pos: 'Other' },
    { id: 'doko3', kana: 'どこか', romaji: 'dokoka', kanji: 'どこか', en: 'Somewhere', morae: 3, pos: 'Adverb' },
    { id: 'dareka', kana: 'だれか', romaji: 'dareka', kanji: '誰か', en: 'Someone', morae: 3, pos: 'Noun' },
    { id: 'nanika', kana: 'なにか', romaji: 'nanika', kanji: '何か', en: 'Something', morae: 3, pos: 'Noun' },
    { id: 'chotto', kana: 'ちょっと', romaji: 'chotto', kanji: 'ちょっと', en: 'A little', morae: 3, pos: 'Adjective' },

    // 4 Morae
    { id: 'tomodachi', kana: 'ともだち', romaji: 'tomodachi', kanji: '友達', en: 'Friend', morae: 4, pos: 'Noun' },
    { id: 'koohii', kana: 'コーヒー', romaji: 'koohii', kanji: '珈琲', en: 'Coffee', morae: 4, pos: 'Noun' },
    { id: 'jitensha', kana: 'じてんしゃ', romaji: 'jitensha', kanji: '自転車', en: 'Bicycle', morae: 4, pos: 'Noun' },
    { id: 'sentou', kana: 'せんとう', romaji: 'sentou', kanji: '銭湯', en: 'Public bath', morae: 4, pos: 'Adjective' },
    { id: 'enpitsu', kana: 'えんぴつ', romaji: 'enpitsu', kanji: '鉛筆', en: 'Pencil', morae: 4, pos: 'Noun' },
    { id: 'keshigomu', kana: 'けしごむ', romaji: 'keshigomu', kanji: '消しゴム', en: 'Eraser', morae: 4, pos: 'Noun' },
    { id: 'hikouki', kana: 'ひこうき', romaji: 'hikouki', kanji: '飛行機', en: 'Airplane', morae: 4, pos: 'Noun' },
    { id: 'kanashii', kana: 'かなしい', romaji: 'kanashii', kanji: '悲しい', en: 'Sad', morae: 4, pos: 'Adjective' },
    { id: 'ureshii', kana: 'うれしい', romaji: 'ureshii', kanji: '嬉しい', en: 'Happy', morae: 4, pos: 'Adjective' },
    { id: 'ookii', kana: 'おおきい', romaji: 'ookii', kanji: '大きい', en: 'Big', morae: 4, pos: 'Adjective' },
    { id: 'chiisai', kana: 'ちいさい', romaji: 'chiisai', kanji: '小さい', en: 'Small', morae: 4, pos: 'Adjective' },
    { id: 'nigiyaka', kana: 'にぎやか', romaji: 'nigiyaka', kanji: '賑やか', en: 'Lively', morae: 4, pos: 'Noun' },
    { id: 'taisetsu', kana: 'たいせつ', romaji: 'taisetsu', kanji: '大切', en: 'Precious', morae: 4, pos: 'Noun' },
    { id: 'anzen', kana: 'あんぜん', romaji: 'anzen', kanji: '安全', en: 'Safe', morae: 4, pos: 'Adjective' },
    { id: 'shippai', kana: 'しっぱい', romaji: 'shippai', kanji: '失敗', en: 'Failure', morae: 4, pos: 'Noun' },
    { id: 'seikou', kana: 'せいこう', romaji: 'seikou', kanji: '成功', en: 'Success', morae: 4, pos: 'Noun' },
    { id: 'takusan', kana: 'たくさん', romaji: 'takusan', kanji: '沢山', en: 'Many / A lot', morae: 4, pos: 'Adjective' },
    { id: 'hotondo', kana: 'ほとんど', romaji: 'hotondo', kanji: '殆ど', en: 'Almost', morae: 4, pos: 'Adverb' },
    { id: 'zenzen', kana: 'ぜんぜん', romaji: 'zenzen', kanji: '全然', en: 'Not at all', morae: 4, pos: 'Adjective' },
    { id: 'tanoshii', kana: 'たのしい', romaji: 'tanoshii', kanji: '楽しい', en: 'Fun', morae: 4, pos: 'Adjective' },
    { id: 'sabishii', kana: 'さびしい', romaji: 'sabishii', kanji: '寂しい', en: 'Lonely', morae: 4, pos: 'Adjective' },
    { id: 'ureshisa', kana: 'うれしさ', romaji: 'ureshisa', kanji: '嬉しさ', en: 'Happiness (noun)', morae: 4, pos: 'Noun' },
    { id: 'kanashimi', kana: 'かなしみ', romaji: 'kanashimi', kanji: '悲しみ', en: 'Sadness', morae: 4, pos: 'Noun' },
    { id: 'yorokobi', kana: 'よろこび', romaji: 'yorokobi', kanji: '喜び', en: 'Joy', morae: 4, pos: 'Noun' },
    { id: 'odoroku', kana: 'おどろく', romaji: 'odoroku', kanji: '驚く', en: 'To be surprised', morae: 4, pos: 'Verb' },
    { id: 'kanjiru', kana: 'かんじる', romaji: 'kanjiru', kanji: '感じる', en: 'To feel', morae: 4, pos: 'Verb' },
    { id: 'yakusoku', kana: 'やくそく', romaji: 'yakusoku', kanji: '約束', en: 'Promise', morae: 4, pos: 'Noun' },
    { id: 'yawaraka', kana: 'やわらか', romaji: 'yawaraka', kanji: '柔らか', en: 'Soft', morae: 4, pos: 'Adjective' },
    { id: 'yasashii', kana: 'やさしい', romaji: 'yasashii', kanji: '優しい', en: 'Kind', morae: 4, pos: 'Adjective' },
    { id: 'hajimeru', kana: 'はじめる', romaji: 'hajimeru', kanji: '始める', en: 'To begin', morae: 4, pos: 'Verb' },
    { id: 'mijikai', kana: 'みじかい', romaji: 'mijikai', kanji: '短い', en: 'Short', morae: 4, pos: 'Adjective' },
    { id: 'wasureru', kana: 'わすれる', romaji: 'wasureru', kanji: '忘れる', en: 'To forget', morae: 4, pos: 'Verb' },
    { id: 'oboeru', kana: 'おぼえる', romaji: 'oboeru', kanji: '覚える', en: 'To remember', morae: 4, pos: 'Verb' },
    { id: 'tasukeru', kana: 'たすける', romaji: 'tasukeru', kanji: '助ける', en: 'To help', morae: 4, pos: 'Verb' },
    { id: 'tsudzukeru', kana: 'つづける', romaji: 'tsudzukeru', kanji: '続ける', en: 'To continue (trans)', morae: 4, pos: 'Verb' },
    { id: 'hajimaru', kana: 'はじまる', romaji: 'hajimaru', kanji: '始まる', en: 'To begin', morae: 4, pos: 'Verb' },
    { id: 'yabureru', kana: 'やぶれる', romaji: 'yabureru', kanji: '破れる', en: 'To tear', morae: 4, pos: 'Verb' },
    { id: 'kawaita', kana: 'かわいた', romaji: 'kawaita', kanji: '乾いた', en: 'Dry (past)', morae: 4, pos: 'Noun' },
    { id: 'yorokobu', kana: 'よろこぶ', romaji: 'yorokobu', kanji: '喜ぶ', en: 'To be happy', morae: 4, pos: 'Verb' },
    { id: 'kanashimu', kana: 'かなしむ', romaji: 'kanashimu', kanji: '悲しむ', en: 'To grieve', morae: 4, pos: 'Verb' },
    { id: 'tanoshimu', kana: 'たのしむ', romaji: 'tanoshimu', kanji: '楽しむ', en: 'To enjoy', morae: 4, pos: 'Verb' },
    { id: 'tsuyomeru', kana: 'つよめる', romaji: 'tsuyomeru', kanji: '強める', en: 'To strengthen', morae: 4, pos: 'Verb' },
    { id: 'yowameru', kana: 'よわめる', romaji: 'yowameru', kanji: '弱める', en: 'To weaken', morae: 4, pos: 'Verb' },
    { id: 'takameru', kana: 'たかめる', romaji: 'takameru', kanji: '高める', en: 'To raise', morae: 4, pos: 'Verb' },
    { id: 'hikumeru', kana: 'ひくめる', romaji: 'hikumeru', kanji: '低める', en: 'To lower', morae: 4, pos: 'Verb' },
    { id: 'hikkosu', kana: 'ひっこす', romaji: 'hikkosu', kanji: '引っ越す', en: 'To move house', morae: 4, pos: 'Verb' },
    { id: 'wasureta', kana: 'わすれた', romaji: 'wasureta', kanji: '忘れた', en: 'Forgot', morae: 4, pos: 'Noun' },
    { id: 'tsukareru', kana: 'つかれる', romaji: 'tsukareru', kanji: '疲れる', en: 'To get tired', morae: 4, pos: 'Verb' },
    { id: 'tasukaru', kana: 'たすかる', romaji: 'tasukaru', kanji: '助かる', en: 'To be saved / helped', morae: 4, pos: 'Verb' },
    { id: 'hikidasu', kana: 'ひきだす', romaji: 'hikidasu', kanji: '引き出す', en: 'To pull out', morae: 4, pos: 'Verb' },
    { id: 'shinjiru', kana: 'しんじる', romaji: 'shinjiru', kanji: '信じる', en: 'To believe', morae: 4, pos: 'Verb' },
    { id: 'ayamaru', kana: 'あやまる', romaji: 'ayamaru', kanji: '謝る', en: 'To apologize', morae: 4, pos: 'Verb' },
    { id: 'aisuru', kana: 'あいする', romaji: 'aisuru', kanji: '愛する', en: 'To love', morae: 4, pos: 'Verb' },
    { id: 'mamoreru', kana: 'まもれる', romaji: 'mamoreru', kanji: '守れる', en: 'Can protect', morae: 4, pos: 'Noun' },
    { id: 'shiranai', kana: 'しらない', romaji: 'shiranai', kanji: '知らない', en: 'Don’t know', morae: 4, pos: 'Noun' },
    { id: 'wakatta', kana: 'わかった', romaji: 'wakatta', kanji: '分かった', en: 'Got it', morae: 4, pos: 'Other' },
    { id: 'hontou', kana: 'ほんとう', romaji: 'hontou', kanji: '本当', en: 'Truth / Really', morae: 4, pos: 'Adverb' },
    { id: 'sensei', kana: 'せんせい', romaji: 'sensei', kanji: '先生', en: 'Teacher', morae: 4, pos: 'Noun' },
    { id: 'gakusei', kana: 'がくせい', romaji: 'gakusei', kanji: '学生', en: 'Student', morae: 4, pos: 'Noun' },
    { id: 'oyasumi', kana: 'おやすみ', romaji: 'oyasumi', kanji: 'お休み', en: 'Good Night', morae: 4, pos: 'Adjective' },
    { id: 'gomenne', kana: 'ごめんね', romaji: 'gomenne', kanji: 'ご免ね', en: 'Sorry', morae: 4, pos: 'Other' },
    { id: 'tanoshii', kana: 'たのしい', romaji: 'tanoshii', kanji: '楽しい', en: 'Fun', morae: 4, pos: 'Adjective' },
    { id: 'yasashii', kana: 'やさしい', romaji: 'yasashii', kanji: '優しい', en: 'Kind', morae: 4, pos: 'Adjective' },
    { id: 'kodomo4', kana: 'こども', romaji: 'kodomo', kanji: '子供', en: 'Child', morae: 4, pos: 'Noun' },
    { id: 'kuruma4', kana: 'くるま', romaji: 'kuruma', kanji: '車', en: 'Car', morae: 4, pos: 'Noun' },
    { id: 'densha4', kana: 'でんしゃ', romaji: 'densha', kanji: '電車', en: 'Train', morae: 4, pos: 'Noun' },
    { id: 'tabako4', kana: 'たばこ', romaji: 'tabako', kanji: '煙草', en: 'Cigarette', morae: 4, pos: 'Noun' },
    { id: 'miruku4', kana: 'みるく', romaji: 'miruku', kanji: 'ミルク', en: 'Milk', morae: 4, pos: 'Noun' },
    { id: 'pasuta4', kana: 'ぱすた', romaji: 'pasuta', kanji: 'パスタ', en: 'Pasta', morae: 4, pos: 'Noun' },
    { id: 'paniru4', kana: 'ばにら', romaji: 'banira', kanji: 'バニラ', en: 'Vanilla', morae: 4, pos: 'Noun' },

    { id: 'gakkou4', kana: 'がっこう', romaji: 'gakkou', kanji: '学校', en: 'School', morae: 4, pos: 'Noun' },
    { id: 'zasshi4', kana: 'ざっし', romaji: 'zasshi', kanji: '雑誌', en: 'Magazine', morae: 4, pos: 'Noun' },
    { id: 'kippu4', kana: 'きっぷ', romaji: 'kippu', kanji: '切符', en: 'Ticket', morae: 4, pos: 'Noun' },
    { id: 'chotto4', kana: 'ちょっと', romaji: 'chotto', kanji: 'ちょっと', en: 'A little', morae: 4, pos: 'Adjective' },
    { id: 'kitte4', kana: 'きって', romaji: 'kitte', kanji: '切手', en: 'Postage stamp', morae: 4, pos: 'Noun' },
    { id: 'sassato4', kana: 'さっさと', romaji: 'sassato', kanji: 'さっさと', en: 'Quickly', morae: 4, pos: 'Adverb' },
    { id: 'zutto4', kana: 'ずっと', romaji: 'zutto', kanji: 'ずっと', en: 'Always / For long time', morae: 4, pos: 'Adverb' },
    { id: 'bikku4', kana: 'びっくり', romaji: 'bikkuri', kanji: '吃驚', en: 'Surprised', morae: 4, pos: 'Adjective' },
    { id: 'yappari4', kana: 'やっぱり', romaji: 'yappari', kanji: 'やはり', en: 'As expected', morae: 4, pos: 'Noun' },
    { id: 'sukoshi4', kana: 'すこし', romaji: 'sukoshi', kanji: '少し', en: 'A little', morae: 4, pos: 'Adjective' },

    { id: 'otona4', kana: 'おとな', romaji: 'otona', kanji: '大人', en: 'Adult', morae: 4, pos: 'Noun' },
    { id: 'kodama4', kana: 'こだま', romaji: 'kodama', kanji: '木霊', en: 'Echo / Tree spirit', morae: 4, pos: 'Noun' },
    { id: 'karada4', kana: 'からだ', romaji: 'karada', kanji: '体', en: 'Body', morae: 4, pos: 'Noun' },
    { id: 'kokoro4', kana: 'こころ', romaji: 'kokoro', kanji: '心', en: 'Heart / Mind', morae: 4, pos: 'Noun' },
    { id: 'tamago4', kana: 'たまご', romaji: 'tamago', kanji: '卵', en: 'Egg', morae: 4, pos: 'Noun' },
    { id: 'sakana4', kana: 'さかな', romaji: 'sakana', kanji: '魚', en: 'Fish', morae: 4, pos: 'Noun' },
    { id: 'yasai4', kana: 'やさい', romaji: 'yasai', kanji: '野菜', en: 'Vegetables', morae: 4, pos: 'Noun' },
    { id: 'futari4', kana: 'ふたり', romaji: 'futari', kanji: '二人', en: 'Two people', morae: 4, pos: 'Noun' },
    { id: 'minami4', kana: 'みなみ', romaji: 'minami', kanji: '南', en: 'South', morae: 4, pos: 'Noun' },
    { id: 'kitano4', kana: 'きたの', romaji: 'kitano', kanji: '北の', en: 'Northern', morae: 4, pos: 'Noun' },

    { id: 'okane4', kana: 'おかね', romaji: 'okane', kanji: 'お金', en: 'Money', morae: 4, pos: 'Noun' },
    { id: 'tegami4', kana: 'てがみ', romaji: 'tegami', kanji: '手紙', en: 'Letter', morae: 4, pos: 'Noun' },
    { id: 'denwa4', kana: 'でんわ', romaji: 'denwa', kanji: '電話', en: 'Phone', morae: 4, pos: 'Noun' },
    { id: 'kaisha4', kana: 'かいしゃ', romaji: 'kaisha', kanji: '会社', en: 'Company', morae: 4, pos: 'Noun' },
    { id: 'ryokou4', kana: 'りょこう', romaji: 'ryokou', kanji: '旅行', en: 'Travel', morae: 4, pos: 'Noun' },
    { id: 'shashin4', kana: 'しゃしん', romaji: 'shashin', kanji: '写真', en: 'Photo', morae: 4, pos: 'Noun' },
    { id: 'byouin4', kana: 'びょういん', romaji: 'byouin', kanji: '病院', en: 'Hospital', morae: 4, pos: 'Noun' },
    { id: 'toshokan4', kana: 'としょかん', romaji: 'toshokan', kanji: '図書館', en: 'Library', morae: 4, pos: 'Noun' },
    { id: 'yakusoku4', kana: 'やくそく', romaji: 'yakusoku', kanji: '約束', en: 'Promise', morae: 4, pos: 'Noun' },
    { id: 'shigoto4', kana: 'しごと', romaji: 'shigoto', kanji: '仕事', en: 'Work', morae: 4, pos: 'Noun' },

    { id: 'benkyou4', kana: 'べんきょう', romaji: 'benkyou', kanji: '勉強', en: 'Study', morae: 4, pos: 'Noun' },
    { id: 'undou4', kana: 'うんどう', romaji: 'undou', kanji: '運動', en: 'Exercise', morae: 4, pos: 'Noun' },
    { id: 'seikatsu4', kana: 'せいかつ', romaji: 'seikatsu', kanji: '生活', en: 'Life / Living', morae: 4, pos: 'Adjective' },
    { id: 'ryouri4', kana: 'りょうり', romaji: 'ryouri', kanji: '料理', en: 'Cooking', morae: 4, pos: 'Noun' },
    { id: 'ongaku4', kana: 'おんがく', romaji: 'ongaku', kanji: '音楽', en: 'Music', morae: 4, pos: 'Noun' },
    { id: 'eigakan4', kana: 'えいがかん', romaji: 'eigakan', kanji: '映画館', en: 'Cinema', morae: 4, pos: 'Noun' },
    { id: 'ashita4', kana: 'あした', romaji: 'ashita', kanji: '明日', en: 'Tomorrow', morae: 4, pos: 'Adverb' },
    { id: 'kinou4', kana: 'きのう', romaji: 'kinou', kanji: '昨日', en: 'Yesterday', morae: 4, pos: 'Adverb' },
    { id: 'asoko4', kana: 'あそこ', romaji: 'asoko', kanji: '彼処', en: 'Over there', morae: 4, pos: 'Adverb' },
    { id: 'dokoka4', kana: 'どこか', romaji: 'dokoka', kanji: '何処か', en: 'Somewhere', morae: 4, pos: 'Adverb' },
    { id: 'nanika4', kana: 'なにか', romaji: 'nanika', kanji: '何か', en: 'Something', morae: 4, pos: 'Noun' },
    { id: 'daremo4', kana: 'だれも', romaji: 'daremo', kanji: '誰も', en: 'Nobody / Everybody (neg)', morae: 4, pos: 'Noun' },
    { id: 'itsu4', kana: 'いつも', romaji: 'itsumo', kanji: 'いつも', en: 'Always', morae: 4, pos: 'Adverb' },
    { id: 'soredemo4', kana: 'それでも', romaji: 'soredemo', kanji: 'それでも', en: 'Even so', morae: 4, pos: 'Adverb' },
    { id: 'dakara4', kana: 'だから', romaji: 'dakara', kanji: 'だから', en: 'So / Therefore', morae: 4, pos: 'Other' },
    { id: 'demo4', kana: 'でもね', romaji: 'demone', kanji: 'でもね', en: 'But you know', morae: 4, pos: 'Other' },
    { id: 'kitto4', kana: 'きっと', romaji: 'kitto', kanji: 'きっと', en: 'Surely', morae: 4, pos: 'Noun' },
    { id: 'zenzen4', kana: 'ぜんぜん', romaji: 'zenzen', kanji: '全然', en: 'Not at all', morae: 4, pos: 'Adjective' },
    { id: 'sukoshi4b', kana: 'すこしも', romaji: 'sukoshimo', kanji: '少しも', en: 'Not even a bit', morae: 4, pos: 'Noun' },

    { id: 'kanashii4', kana: 'かなしい', romaji: 'kanashii', kanji: '悲しい', en: 'Sad', morae: 4, pos: 'Adjective' },
    { id: 'ureshii4', kana: 'うれしい', romaji: 'ureshii', kanji: '嬉しい', en: 'Happy', morae: 4, pos: 'Adjective' },
    { id: 'atsui4', kana: 'あついね', romaji: 'atsuine', kanji: '暑いね', en: 'It’s hot, huh', morae: 4, pos: 'Noun' },
    { id: 'samui4b', kana: 'さむいよ', romaji: 'samuiyo', kanji: '寒いよ', en: 'It’s cold', morae: 4, pos: 'Adjective' },
    { id: 'itai4', kana: 'いたいよ', romaji: 'itaiyo', kanji: '痛いよ', en: 'It hurts', morae: 4, pos: 'Other' },
    { id: 'kowai4', kana: 'こわいよ', romaji: 'kowaiyo', kanji: '怖いよ', en: 'Scary', morae: 4, pos: 'Noun' },
    { id: 'oishii4', kana: 'おいしい', romaji: 'oishii', kanji: '美味しい', en: 'Delicious', morae: 4, pos: 'Adjective' },
    { id: 'mazui4', kana: 'まずいね', romaji: 'mazuine', kanji: '不味いね', en: 'Tastes bad', morae: 4, pos: 'Adjective' },
    { id: 'nemui4', kana: 'ねむいよ', romaji: 'nemuiyo', kanji: '眠いよ', en: 'Sleepy', morae: 4, pos: 'Adjective' },
    { id: 'omoshiroi4', kana: 'おもしろい', romaji: 'omoshiroi', kanji: '面白い', en: 'Interesting', morae: 4, pos: 'Adjective' },

    { id: 'kirei4', kana: 'きれいね', romaji: 'kireine', kanji: '綺麗ね', en: 'Pretty', morae: 4, pos: 'Adjective' },
    { id: 'daijoubu4', kana: 'だいじょうぶ', romaji: 'daijoubu', kanji: '大丈夫', en: 'It’s okay', morae: 4, pos: 'Other' },
    { id: 'mada4', kana: 'まだだよ', romaji: 'madadayo', kanji: 'まだだよ', en: 'Not yet', morae: 4, pos: 'Adverb' },
    { id: 'hayaku4', kana: 'はやくね', romaji: 'hayakune', kanji: '早くね', en: 'Hurry up', morae: 4, pos: 'Noun' },
    { id: 'sugoi4', kana: 'すごいね', romaji: 'sugoine', kanji: '凄いね', en: 'Amazing', morae: 4, pos: 'Adjective' },
    { id: 'taihen4', kana: 'たいへん', romaji: 'taihen', kanji: '大変', en: 'Hard / Serious', morae: 4, pos: 'Adjective' },
    { id: 'heiki4', kana: 'へいきだよ', romaji: 'heikidayo', kanji: '平気だよ', en: 'I’m fine', morae: 4, pos: 'Noun' },
    { id: 'yabai4', kana: 'やばいね', romaji: 'yabaine', kanji: 'やばいね', en: 'Oh no / Crazy', morae: 4, pos: 'Adjective' },
    { id: 'majide4', kana: 'まじで', romaji: 'majide', kanji: 'マジで', en: 'Seriously?', morae: 4, pos: 'Noun' },
    { id: 'uso4', kana: 'うそだよ', romaji: 'usodayo', kanji: '嘘だよ', en: 'Just kidding', morae: 4, pos: 'Adjective' },

    // 5 Morae
    { id: 'atarashii', kana: 'あたらしい', romaji: 'atarashii', kanji: '新しい', en: 'New', morae: 5, pos: 'Adjective' },
    { id: 'omoshiroi', kana: 'おもしろい', romaji: 'omoshiroi', kanji: '面白い', en: 'Interesting', morae: 5, pos: 'Adjective' },
    { id: 'muzukashii', kana: 'むずかしい', romaji: 'muzukashii', kanji: '難しい', en: 'Difficult', morae: 5, pos: 'Adjective' },
    { id: 'atarashiku', kana: 'あたらしく', romaji: 'atarashiku', kanji: '新しく', en: 'Newly', morae: 5, pos: 'Noun' },
    { id: 'kangaeru', kana: 'かんがえる', romaji: 'kangaeru', kanji: '考える', en: 'To think', morae: 5, pos: 'Verb' },
    { id: 'omoidashi', kana: 'おもいだし', romaji: 'omoidashi', kanji: '思い出し', en: 'Recall (stem)', morae: 5, pos: 'Noun' },
    { id: 'omoidasu', kana: 'おもいだす', romaji: 'omoidasu', kanji: '思い出す', en: 'To remember', morae: 5, pos: 'Verb' },
    { id: 'wakaranai', kana: 'わからない', romaji: 'wakaranai', kanji: '分からない', en: 'Don’t understand', morae: 5, pos: 'Noun' },
    { id: 'daijoubu', kana: 'だいじょうぶ', romaji: 'daijoubu', kanji: '大丈夫', en: 'Okay / Fine', morae: 5, pos: 'Other' },
    { id: 'arigatou', kana: 'ありがとう', romaji: 'arigatou', kanji: '有難う', en: 'Thank You', morae: 5, pos: 'Other' },
    { id: 'sayounara', kana: 'さようなら', romaji: 'sayounara', kanji: '左様なら', en: 'Goodbye', morae: 5, pos: 'Other' },
    { id: 'konnichiwa', kana: 'こんにちは', romaji: 'konnichiwa', kanji: '今日は', en: 'Hello', morae: 5, pos: 'Other' },
    { id: 'konbanwa', kana: 'こんばんは', romaji: 'konbanwa', kanji: '今晩は', en: 'Good Evening', morae: 5, pos: 'Adjective' },
    { id: 'sumimasen', kana: 'すみません', romaji: 'sumimasen', kanji: '済みません', en: 'Excuse Me', morae: 5, pos: 'Other' },
    { id: 'daijoubu', kana: 'だいじょうぶ', romaji: 'daijoubu', kanji: '大丈夫', en: 'Okay', morae: 5, pos: 'Other' },
    { id: 'omoshiroi', kana: 'おもしろい', romaji: 'omoshiroi', kanji: '面白い', en: 'Interesting', morae: 5, pos: 'Adjective' },
    { id: 'muzukashii', kana: 'むずかしい', romaji: 'muzukashii', kanji: '難しい', en: 'Difficult', morae: 5, pos: 'Adjective' },
    { id: 'natsukashii', kana: 'なつかしい', romaji: 'natsukashii', kanji: '懐かしい', en: 'Nostalgic', morae: 5, pos: 'Noun' },
    // 6 Morae
    { id: 'itadakimasu', kana: 'いただきます', romaji: 'itadakimasu', kanji: '頂きます', en: 'Bon Appétit', morae: 6, pos: 'Noun' },
    { id: 'gochisousama', kana: 'ごちそうさま', romaji: 'gochisousama', kanji: 'ご馳走様', en: 'Thanks for food', morae: 6, pos: 'Other' },
];
